### ISSUE TITLE
404 links in CAPI-Docker post 

### ISSUE THREAD

**Issue by Callisto13** [networkop/networkop.github.io#3]
👋 

"The book" links on [line 332](https://github.com/networkop/networkop.github.io/blob/39ada6b56157a979774e1b5ef5750dd1367a0587/post/2020-05-cluster-api-intro/index.html#L332) and [line 369](https://github.com/networkop/networkop.github.io/blob/39ada6b56157a979774e1b5ef5750dd1367a0587/post/2020-05-cluster-api-intro/index.html#L369) don't go anywhere.

😁

**Comment by networkop** [comment]
oops

**Comment by networkop** [comment]
fixed thanks!
