### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by itdependsnetworks** [networkop/networkop.github.io#4]
I see that when you switched to hugo several years ago, the auto-generation of RSS stopped. Any appetite to add that functionality back? Or perhaps it is hosted at another url?

**Comment by networkop** [comment]
ha! i didn't realise that... need to investigate, thanks for the heads-up 👍

**Comment by networkop** [comment]
@itdependsnetworks what are you using as RSS reader? It seems like RSS does work [with some minor issues](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnetworkop.co.uk)

**Comment by itdependsnetworks** [comment]
I guess this falls into the `Or perhaps it is hosted at another url?` category. I looked for an rss link and didn't immediately find it, thanks!

**Comment by networkop** [comment]
I should probably add an icon with a link to it...
